# Generated by Django 4.2 on 2026-03-29 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=10)),
                ('to_currency', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('result', models.FloatField()),
                ('rate', models.FloatField()),
                ('method', models.CharField(default='voice', max_length=20)),
                ('operator', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'عملية صرف',
                'verbose_name_plural': 'عمليات الصرف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('user_id', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'صورة مرفوعة',
                'verbose_name_plural': 'الصور المرفوعة',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
