# Generated by Django 4.2 on 2026-03-29 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_exchangeoperation_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('withdrawal', 'سحب'), ('deposit', 'إيداع')], max_length=20, verbose_name='النوع')),
                ('client_name', models.CharField(max_length=200, verbose_name='اسم العميل')),
                ('account', models.CharField(blank=True, max_length=100, verbose_name='الحساب')),
                ('amount', models.FloatField(verbose_name='المبلغ')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='العملة')),
                ('operator', models.CharField(blank=True, max_length=100, verbose_name='التلر')),
                ('method', models.CharField(default='voice', max_length=20, verbose_name='الطريقة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'معاملة نقدية',
                'verbose_name_plural': 'المعاملات النقدية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HawalaOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=200, verbose_name='اسم المرسل')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='اسم المستلم')),
                ('amount', models.FloatField(verbose_name='المبلغ')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='العملة')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='الوجهة')),
                ('operator', models.CharField(blank=True, max_length=100, verbose_name='التلر')),
                ('method', models.CharField(default='voice', max_length=20, verbose_name='الطريقة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'حوالة',
                'verbose_name_plural': 'الحوالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
