# Generated by Django 4.2 on 2026-03-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_cashtransaction_hawalaoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashtransaction',
            name='web_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exchangeoperation',
            name='web_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hawalaoperation',
            name='web_applied',
            field=models.BooleanField(default=False),
        ),
    ]
