# Generated by Django 4.2 on 2026-03-31 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_cashtransaction_web_applied_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_by', models.CharField(blank=True, max_length=150, verbose_name='نشر بواسطة')),
                ('rates_json', models.JSONField(default=dict, verbose_name='بيانات الأسعار')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'أسعار صرف',
                'verbose_name_plural': 'سجلات أسعار الصرف',
                'ordering': ['-created_at'],
            },
        ),
    ]
