# Generated by Django 4.2 on 2026-03-31 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TellerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=60, unique=True)),
                ('request_type', models.CharField(choices=[('special_price', 'سعر مميز'), ('urgent', 'عاجل'), ('general', 'عام'), ('balance', 'رصيد')], default='general', max_length=20)),
                ('teller_name', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('requested_rate', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'بانتظار'), ('approved', 'موافق'), ('rejected', 'مرفوض'), ('resolved', 'تم الرد')], default='pending', max_length=15)),
                ('reply', models.TextField(blank=True)),
                ('resolved_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'طلب تلر',
                'verbose_name_plural': 'طلبات التلرات',
                'ordering': ['-created_at'],
            },
        ),
    ]
