# Generated by Django 4.2 on 2026-04-01 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_teller_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='TellerBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teller_username', models.CharField(max_length=150, verbose_name='اسم المستخدم للتلر')),
                ('teller_name', models.CharField(blank=True, max_length=150, verbose_name='الاسم المعروض')),
                ('usd', models.FloatField(default=0, verbose_name='دولار')),
                ('ils', models.FloatField(default=0, verbose_name='شيكل')),
                ('jod', models.FloatField(default=0, verbose_name='دينار')),
                ('action', models.CharField(choices=[('set', 'تعيين'), ('add', 'إضافة')], default='set', max_length=5)),
                ('set_by', models.CharField(blank=True, max_length=150, verbose_name='عُيِّن بواسطة')),
                ('session_id', models.CharField(blank=True, max_length=60, verbose_name='معرف الجلسة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'رصيد تلر',
                'verbose_name_plural': 'أرصدة التلرات',
                'ordering': ['-created_at'],
            },
        ),
    ]
