# Generated by Django 4.2 on 2026-04-01 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_teller_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teller_id', models.CharField(max_length=10, unique=True, verbose_name='رقم التلر')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم المعروض')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='اسم المستخدم')),
                ('status', models.CharField(default='offline', max_length=10, verbose_name='الحالة')),
                ('balance', models.FloatField(default=0, verbose_name='رصيد الصندوق (دولار تقريبي)')),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('ops', models.IntegerField(default=0, verbose_name='عمليات اليوم')),
                ('login_time', models.CharField(default='—', max_length=20, verbose_name='وقت الدخول')),
                ('last_op', models.CharField(default='—', max_length=20, verbose_name='آخر عملية')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'ملف تلر',
                'verbose_name_plural': 'ملفات التلرات',
                'ordering': ['teller_id'],
            },
        ),
    ]
