# Generated by Django 4.2 on 2026-04-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_teller_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tellerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
    ]
