# Generated by Django 4.2 on 2026-04-01 13:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_teller_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='TellerPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teller_username', models.CharField(max_length=150, unique=True, verbose_name='اسم المستخدم')),
                ('exchange', models.BooleanField(default=True, verbose_name='قسم الصرافة')),
                ('international', models.BooleanField(default=True, verbose_name='الحوالات الدولية')),
                ('electronic', models.BooleanField(default=True, verbose_name='المعاملات الإلكترونية')),
                ('special_price', models.BooleanField(default=False, verbose_name='السعر المميز')),
                ('double_delivery', models.BooleanField(default=False, verbose_name='التسليم المزدوج')),
                ('updated_by', models.CharField(blank=True, max_length=150, verbose_name='عُدِّل بواسطة')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'صلاحيات تلر',
                'verbose_name_plural': 'صلاحيات التلرات',
            },
        ),
    ]
