# Generated by Django 4.2 on 2026-04-04 13:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_teller_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الفرع')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='الموقع')),
                ('currency', models.CharField(default='USD', max_length=5, verbose_name='العملة الأساسية')),
                ('balance_usd', models.FloatField(default=0, verbose_name='رصيد دولار')),
                ('balance_ils', models.FloatField(default=0, verbose_name='رصيد شيكل')),
                ('balance_jod', models.FloatField(default=0, verbose_name='رصيد دينار')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('pending', 'قيد الإنشاء')], default='active', max_length=10, verbose_name='الحالة')),
                ('manager', models.CharField(blank=True, max_length=150, verbose_name='مدير الفرع')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='هاتف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='المبلغ')),
                ('currency', models.CharField(default='USD', max_length=5, verbose_name='العملة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='بواسطة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_out', to='pages.branch', verbose_name='من فرع')),
                ('to_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_in', to='pages.branch', verbose_name='إلى فرع')),
            ],
            options={
                'verbose_name': 'تحويل فرع',
                'verbose_name_plural': 'تحويلات الفروع',
                'ordering': ['-created_at'],
            },
        ),
    ]
