# Generated by Django 4.2 on 2026-04-05 07:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_branch_branchtransfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='نص التعليمة')),
                ('priority', models.CharField(choices=[('normal', 'عادية'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='normal', max_length=10, verbose_name='الأولوية')),
                ('target_role', models.CharField(blank=True, max_length=5, verbose_name='الدور المستهدف (فارغ = كل المشرفين)')),
                ('target_user', models.CharField(blank=True, max_length=150, verbose_name='المستخدم المستهدف (اختياري)')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('read_by', models.CharField(blank=True, max_length=150, verbose_name='قرأها')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='أنشأها')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'تعليمة إدارية',
                'verbose_name_plural': 'تعليمات الإدارة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=30, unique=True, verbose_name='رقم العملية')),
                ('transfer_type', models.CharField(choices=[('incoming', 'حوالة واردة'), ('outgoing', 'تحويل صادر'), ('buy', 'شراء عبر البنك'), ('sell', 'بيع عبر البنك')], max_length=10, verbose_name='النوع')),
                ('sender_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المرسل/المشتري')),
                ('receiver_name', models.CharField(blank=True, max_length=200, verbose_name='اسم المستلم/البائع')),
                ('amount', models.FloatField(verbose_name='المبلغ')),
                ('currency', models.CharField(default='USD', max_length=5, verbose_name='العملة')),
                ('exchange_rate', models.FloatField(default=1, verbose_name='سعر الصرف')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='اسم البنك')),
                ('account_number', models.CharField(blank=True, max_length=100, verbose_name='رقم الحساب')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('swift_code', models.CharField(blank=True, max_length=20, verbose_name='SWIFT')),
                ('status', models.CharField(choices=[('pending', 'بانتظار'), ('completed', 'مكتمل'), ('cancelled', 'ملغى'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='أنشأها')),
                ('completed_by', models.CharField(blank=True, max_length=150, verbose_name='أكملها')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تحويل بنكي',
                'verbose_name_plural': 'التحويلات البنكية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المجموعة')),
                ('color', models.CharField(default='#32b8c6', max_length=20, verbose_name='اللون')),
                ('icon', models.CharField(default='👥', max_length=10, verbose_name='الأيقونة')),
                ('description', models.TextField(blank=True, verbose_name='وصف')),
                ('count', models.IntegerField(default=0, verbose_name='عدد العملاء')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='أنشأها')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'مجموعة عملاء',
                'verbose_name_plural': 'مجموعات العملاء',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الوكيل')),
                ('color', models.CharField(default='#34d399', max_length=20, verbose_name='اللون')),
                ('icon', models.CharField(default='🤝', max_length=10, verbose_name='الأيقونة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('busy', 'مشغول'), ('offline', 'غير متاح')], default='active', max_length=10, verbose_name='الحالة')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('currencies', models.CharField(default='USD,ILS,JOD', max_length=100, verbose_name='العملات المدعومة')),
                ('commission', models.FloatField(default=0.0, verbose_name='عمولة %')),
                ('max_capacity', models.IntegerField(default=50, verbose_name='الطاقة القصوى')),
                ('current_load', models.IntegerField(default=0, verbose_name='التحميل الحالي')),
                ('responsible', models.CharField(blank=True, max_length=150, verbose_name='المسؤول')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='أنشأه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'وكيل تنفيذ',
                'verbose_name_plural': 'وكلاء التنفيذ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('tellerMgr', 'مشرف التلر'), ('tellerDept', 'أقسام التلر'), ('transSuper', 'مشرف الحوالات'), ('transactions', 'الحوالات'), ('bankTransfer', 'التحويل البنكي')], max_length=20, verbose_name='الصفحة')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان التقرير')),
                ('body', models.TextField(verbose_name='محتوى التقرير')),
                ('branch', models.CharField(blank=True, max_length=200, verbose_name='الفرع')),
                ('submitted_by', models.CharField(blank=True, max_length=150, verbose_name='قدّمه')),
                ('is_read', models.BooleanField(default=False, verbose_name='قرأه المدير')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'تقرير مشرف',
                'verbose_name_plural': 'تقارير المشرفين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HawalaTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=30, unique=True, verbose_name='رقم الحوالة')),
                ('sender_name', models.CharField(max_length=200, verbose_name='اسم المرسل')),
                ('sender_phone', models.CharField(blank=True, max_length=30, verbose_name='هاتف المرسل')),
                ('receiver_name', models.CharField(max_length=200, verbose_name='اسم المستلم')),
                ('receiver_phone', models.CharField(blank=True, max_length=30, verbose_name='هاتف المستلم')),
                ('amount', models.FloatField(verbose_name='المبلغ')),
                ('currency', models.CharField(default='USD', max_length=5, verbose_name='العملة')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='الوجهة')),
                ('status', models.CharField(choices=[('pending', 'بانتظار'), ('processing', 'قيد التنفيذ'), ('completed', 'تم التنفيذ'), ('cancelled', 'ملغاة'), ('rejected', 'مرفوضة')], default='pending', max_length=15, verbose_name='الحالة')),
                ('commission', models.FloatField(default=0, verbose_name='العمولة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='أنشأها')),
                ('completed_by', models.CharField(blank=True, max_length=150, verbose_name='نفّذها')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.executionagent', verbose_name='الوكيل المنفذ')),
                ('client_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.clientgroup', verbose_name='مجموعة العميل')),
            ],
            options={
                'verbose_name': 'حوالة',
                'verbose_name_plural': 'الحوالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
