# Generated by Django 4.2 on 2026-04-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_admininstruction_banktransfer_clientgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'بانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغى'), ('rejected', 'مرفوض')], default='pending', max_length=15, verbose_name='الحالة'),
        ),
    ]
