# Generated by Django 4.2 on 2026-04-12 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_banktransfer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('login_failed', 'محاولة دخول فاشلة'), ('bk_create', 'إنشاء تحويل بنكي'), ('bk_complete', 'تنفيذ تحويل بنكي'), ('bk_reject', 'رفض تحويل بنكي'), ('bk_status', 'تغيير حالة تحويل بنكي'), ('tl_exchange', 'عملية صرافة'), ('tl_hawala', 'حوالة دولية'), ('tl_cash', 'إيداع/سحب نقدي'), ('tl_session_open', 'فتح جلسة تلر'), ('tl_session_close', 'إغلاق جلسة تلر'), ('ts_create', 'إنشاء حوالة'), ('ts_update', 'تعديل حوالة'), ('ts_delete', 'حذف حوالة'), ('user_create', 'إنشاء مستخدم'), ('user_update', 'تعديل مستخدم'), ('user_delete', 'حذف مستخدم'), ('user_password', 'تغيير كلمة مرور'), ('branch_create', 'إنشاء فرع'), ('branch_update', 'تعديل فرع'), ('branch_transfer', 'تحويل رصيد بين فروع'), ('other', 'أخرى')], max_length=30, verbose_name='الإجراء')),
                ('actor', models.CharField(max_length=150, verbose_name='المنفِّذ')),
                ('actor_role', models.CharField(blank=True, max_length=10, verbose_name='دوره')),
                ('target', models.CharField(blank=True, max_length=300, verbose_name='الهدف')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(blank=True, max_length=5)),
                ('detail', models.TextField(blank=True, verbose_name='تفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'سجل مراجعة',
                'verbose_name_plural': 'سجل المراجعة',
                'ordering': ['-created_at'],
            },
        ),
    ]
