# Generated by Django 4.2 on 2026-04-12 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'رمز دخول — البوابة',
                'verbose_name_plural': 'رموز الدخول — البوابة',
                'ordering': ['-created_at'],
            },
        ),
    ]
