# Generated by Django 4.2 on 2026-04-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_portal_transfer_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('type', models.CharField(choices=[('improve', 'تحسين'), ('feature', 'ميزة جديدة'), ('bug', 'بلاغ خطأ')], default='improve', max_length=10, verbose_name='النوع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('in_progress', 'قيد التنفيذ'), ('done', 'منجز'), ('rejected', 'مرفوض')], default='new', max_length=12, verbose_name='الحالة')),
                ('sender', models.CharField(max_length=150, verbose_name='المُرسِل (username)')),
                ('sender_role', models.CharField(max_length=3, verbose_name='دور المُرسِل')),
                ('sender_page', models.CharField(blank=True, max_length=100, verbose_name='الصفحة المُرسِلة')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'طلب تطوير',
                'verbose_name_plural': 'طلبات التطوير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='portalcountry',
            name='rate_note',
            field=models.CharField(blank=True, help_text='مثال: 1 USD = 3.75 SAR', max_length=200, verbose_name='ملاحظة السعر'),
        ),
        migrations.AlterField(
            model_name='portaltransferrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
