# Generated by Django 4.2 on 2026-04-14 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_dev_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaltransferrequest',
            name='forwarded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت التوجيه'),
        ),
        migrations.AddField(
            model_name='portaltransferrequest',
            name='forwarded_by',
            field=models.CharField(blank=True, max_length=150, verbose_name='وجَّهه'),
        ),
        migrations.AddField(
            model_name='portaltransferrequest',
            name='forwarded_note',
            field=models.TextField(blank=True, verbose_name='ملاحظة التوجيه'),
        ),
        migrations.AddField(
            model_name='portaltransferrequest',
            name='forwarded_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_receipts', to=settings.AUTH_USER_MODEL, verbose_name='موجَّه إلى'),
        ),
    ]
