# Generated by Django 4.2 on 2026-04-15 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_forward_portal_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralTreasury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_usd', models.FloatField(default=0, verbose_name='رصيد دولار')),
                ('balance_ils', models.FloatField(default=0, verbose_name='رصيد شيكل')),
                ('balance_jod', models.FloatField(default=0, verbose_name='رصيد دينار')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'الخزينة المركزية',
                'verbose_name_plural': 'الخزينة المركزية',
            },
        ),
        migrations.CreateModel(
            name='TreasuryDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='المبلغ')),
                ('currency', models.CharField(choices=[('USD', 'دولار'), ('ILS', 'شيكل'), ('JOD', 'دينار')], default='USD', max_length=3)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظة')),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'إيداع خزينة',
                'verbose_name_plural': 'إيداعات الخزينة',
                'ordering': ['-created_at'],
            },
        ),
    ]
