# Generated by Django 4.2 on 2026-04-18 07:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_central_treasury'),
    ]

    operations = [
        migrations.AddField(
            model_name='hawalatransfer',
            name='agent_confirmed',
            field=models.BooleanField(default=False, verbose_name='أكد الوكيل التنفيذ'),
        ),
        migrations.AddField(
            model_name='hawalatransfer',
            name='agent_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت تأكيد الوكيل'),
        ),
        migrations.AddField(
            model_name='hawalatransfer',
            name='frozen_usdt',
            field=models.FloatField(default=0, verbose_name='USDT مجمّد عند الوكيل'),
        ),
        migrations.AddField(
            model_name='hawalatransfer',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='مستعجل'),
        ),
        migrations.CreateModel(
            name='AgentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hawala_ref', models.CharField(blank=True, max_length=50, verbose_name='رقم الحوالة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='صورة الإيصال')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('verified_by', models.CharField(blank=True, max_length=150, verbose_name='تحقق بواسطة')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت التحقق')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='pages.executionagent', verbose_name='الوكيل')),
                ('transfer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='pages.hawalatransfer', verbose_name='الحوالة')),
            ],
            options={
                'verbose_name': 'إيصال تنفيذ',
                'verbose_name_plural': 'إيصالات التنفيذ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('deposit', 'إيداع'), ('deduct', 'خصم - تنفيذ حوالة'), ('commission', 'عمولة'), ('refund', 'استرداد')], max_length=15, verbose_name='نوع العملية')),
                ('amount_usdt', models.FloatField(verbose_name='المبلغ USDT')),
                ('balance_after', models.FloatField(default=0, verbose_name='الرصيد بعد العملية')),
                ('hawala_ref', models.CharField(blank=True, max_length=50, verbose_name='رقم الحوالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='بواسطة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_logs', to='pages.executionagent', verbose_name='الوكيل')),
            ],
            options={
                'verbose_name': 'رصيد وكيل',
                'verbose_name_plural': 'أرصدة الوكلاء',
                'ordering': ['-created_at'],
            },
        ),
    ]
