# Generated by Django 4.2 on 2026-04-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_hawalatransfer_agent_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='totp_enabled',
            field=models.BooleanField(default=False, verbose_name='2FA مفعّل'),
        ),
        migrations.AddField(
            model_name='systemuser',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, verbose_name='مفتاح 2FA'),
        ),
    ]
