# Generated by Django 4.2 on 2026-04-21 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_systemuser_totp_enabled_systemuser_totp_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان المهمة')),
                ('description', models.TextField(verbose_name='الوصف التفصيلي')),
                ('priority', models.CharField(choices=[('low', 'عادية'), ('medium', 'مهمة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('new', 'جديدة'), ('in_progress', 'قيد التنفيذ'), ('submitted', 'مُسلَّمة'), ('accepted', 'مقبولة'), ('rejected', 'مرفوضة')], default='new', max_length=15, verbose_name='الحالة')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='الموعد النهائي')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tasks/attachments/%Y/%m/', verbose_name='مرفق من المدير')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة عند الرفض')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مُكلَّف به')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='أنشأها')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='ملاحظات التسليم')),
                ('file', models.FileField(blank=True, null=True, upload_to='tasks/submissions/%Y/%m/', verbose_name='ملف التنفيذ')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to=settings.AUTH_USER_MODEL, verbose_name='قدّمه')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='pages.task', verbose_name='المهمة')),
            ],
            options={
                'verbose_name': 'تسليم مهمة',
                'verbose_name_plural': 'تسليمات المهام',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='نص التعليق')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pages.task', verbose_name='المهمة')),
            ],
            options={
                'verbose_name': 'تعليق مهمة',
                'verbose_name_plural': 'تعليقات المهام',
                'ordering': ['created_at'],
            },
        ),
    ]
