# Generated by Django 4.2 on 2026-04-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_task_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='role',
            field=models.CharField(choices=[('M01', 'الإدارة العامة'), ('M02', 'مشرف التلر'), ('M03', 'مشرف الحوالات'), ('T01', 'أقسام التلر'), ('T02', 'التحويل البنكي'), ('T03', 'الحوالات الخارجية'), ('IM01', 'مدير المبرمجين'), ('P01', 'مبرمج')], default='T01', max_length=4, verbose_name='الصلاحية'),
        ),
    ]
