# Generated by Django 4.2 on 2026-04-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_role_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentbalance',
            name='amount_usdt',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='المبلغ USDT'),
        ),
        migrations.AlterField(
            model_name='agentbalance',
            name='balance_after',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='الرصيد بعد العملية'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='banktransfer',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=14, verbose_name='سعر الصرف'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='balance_ils',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='رصيد شيكل'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='balance_jod',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='رصيد دينار'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='balance_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='رصيد دولار'),
        ),
        migrations.AlterField(
            model_name='branchtransfer',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='cashtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='centraltreasury',
            name='balance_ils',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='رصيد شيكل'),
        ),
        migrations.AlterField(
            model_name='centraltreasury',
            name='balance_jod',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='رصيد دينار'),
        ),
        migrations.AlterField(
            model_name='centraltreasury',
            name='balance_usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='رصيد دولار'),
        ),
        migrations.AlterField(
            model_name='exchangeoperation',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='exchangeoperation',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='exchangeoperation',
            name='result',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
        migrations.AlterField(
            model_name='executionagent',
            name='commission',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='عمولة %'),
        ),
        migrations.AlterField(
            model_name='hawalaoperation',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='hawalatransfer',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='hawalatransfer',
            name='commission',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='العمولة'),
        ),
        migrations.AlterField(
            model_name='hawalatransfer',
            name='frozen_usdt',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='USDT مجمّد عند الوكيل'),
        ),
        migrations.AlterField(
            model_name='tellerbalance',
            name='ils',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='شيكل'),
        ),
        migrations.AlterField(
            model_name='tellerbalance',
            name='jod',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='دينار'),
        ),
        migrations.AlterField(
            model_name='tellerbalance',
            name='usd',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='دولار'),
        ),
        migrations.AlterField(
            model_name='tellerprofile',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='رصيد الصندوق (دولار تقريبي)'),
        ),
        migrations.AlterField(
            model_name='treasurydeposit',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=14, verbose_name='المبلغ'),
        ),
    ]
