# Generated by Django 4.2 on 2026-04-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_hawala_cash_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hawalatransfer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الحذف'),
        ),
        migrations.AddField(
            model_name='hawalatransfer',
            name='deleted_by',
            field=models.CharField(blank=True, max_length=150, verbose_name='حذفها'),
        ),
        migrations.AddField(
            model_name='hawalatransfer',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف'),
        ),
    ]
