# Generated by Django 4.2 on 2026-04-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_hawala_soft_delete'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['operator', 'created_at'], name='cash_operator_date_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['transaction_type'], name='cash_type_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeoperation',
            index=models.Index(fields=['operator', 'created_at'], name='ex_op_operator_date_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangeoperation',
            index=models.Index(fields=['created_at'], name='ex_op_date_idx'),
        ),
        migrations.AddIndex(
            model_name='hawalaoperation',
            index=models.Index(fields=['operator', 'created_at'], name='hw_op_operator_date_idx'),
        ),
        migrations.AddIndex(
            model_name='hawalatransfer',
            index=models.Index(fields=['status', 'created_at'], name='hw_tr_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='hawalatransfer',
            index=models.Index(fields=['agent', 'status'], name='hw_tr_agent_status_idx'),
        ),
        migrations.AddIndex(
            model_name='hawalatransfer',
            index=models.Index(fields=['is_deleted'], name='hw_tr_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='tellerbalance',
            index=models.Index(fields=['teller_username', 'action', 'created_at'], name='tbal_username_action_idx'),
        ),
    ]
