# Generated by Django 4.2 on 2026-04-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0028_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='rate_type',
            field=models.CharField(choices=[('teller', 'تلر — صرافة'), ('hawala', 'حوالات')], db_index=True, default='teller', max_length=20, verbose_name='نوع الأسعار'),
        ),
    ]
