# Generated by Django 4.2 on 2026-04-28 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_exchangerate_rate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlutterAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='hash الـ token')),
                ('device_id', models.CharField(blank=True, default='', max_length=200, verbose_name='معرف الجهاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flutter_tokens', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة Flutter',
                'verbose_name_plural': 'جلسات Flutter',
                'ordering': ['-created_at'],
            },
        ),
    ]
