# Generated by Django 4.2 on 2026-04-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_flutter_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalcountry',
            name='fee_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مثال: 2.5 تعني 2.5%، 0 تعني بدون عمولة', max_digits=5, verbose_name='نسبة العمولة %'),
        ),
    ]
