# Generated by Django 4.2 on 2026-04-29 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_portal_country_fee_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZKDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='الجهاز الرئيسي', max_length=100, verbose_name='اسم الجهاز')),
                ('ip', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('port', models.PositiveIntegerField(default=4370, verbose_name='المنفذ')),
                ('password', models.PositiveIntegerField(default=0, verbose_name='كلمة المرور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='آخر مزامنة')),
            ],
            options={
                'verbose_name': 'جهاز بصمة',
                'verbose_name_plural': 'أجهزة البصمة',
            },
        ),
        migrations.CreateModel(
            name='ZKEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.PositiveIntegerField(verbose_name='رقم في الجهاز')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('user_id', models.CharField(max_length=50, verbose_name='معرف المستخدم')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='pages.zkdevice', verbose_name='الجهاز')),
                ('system_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zk_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب النظام')),
            ],
            options={
                'verbose_name': 'موظف البصمة',
                'verbose_name_plural': 'موظفو البصمة',
                'unique_together': {('device', 'uid')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, verbose_name='معرف المستخدم')),
                ('timestamp', models.DateTimeField(verbose_name='وقت البصمة')),
                ('punch', models.SmallIntegerField(choices=[(0, 'دخول'), (1, 'خروج'), (4, 'استراحة خروج'), (5, 'استراحة دخول')], default=0, verbose_name='نوع البصمة')),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت المزامنة')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='pages.zkdevice', verbose_name='الجهاز')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='pages.zkemployee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'ordering': ['-timestamp'],
                'unique_together': {('device', 'user_id', 'timestamp')},
            },
        ),
    ]
