# Generated by Django 4.2 on 2026-05-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0038_whatsappmessage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentlocation',
            name='unique_agent_location',
        ),
        migrations.RemoveConstraint(
            model_name='agenttransferrate',
            name='unique_agent_country_currency',
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='has_image',
            field=models.BooleanField(default=False, verbose_name='تحتوي صورة'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='matched_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='كود الحوالة المطابق'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='agentlocation',
            unique_together={('agent', 'country', 'city')},
        ),
        migrations.AlterUniqueTogether(
            name='agenttransferrate',
            unique_together={('agent', 'country', 'currency')},
        ),
    ]
