# Generated by Django 4.2 on 2026-05-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_whatsappmessage_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='صورة الإيصال'),
        ),
    ]
