# Generated by Django 4.2 on 2026-05-10 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_attendancerecord_manual_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySwap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=30, unique=True, verbose_name='رقم العملية')),
                ('center1_name', models.CharField(max_length=200, verbose_name='المركز الأول')),
                ('center2_name', models.CharField(max_length=200, verbose_name='المركز الثاني')),
                ('currency1', models.CharField(max_length=10, verbose_name='عملة المركز الأول')),
                ('currency2', models.CharField(max_length=10, verbose_name='عملة المركز الثاني')),
                ('amount1', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='مبلغ المركز الأول')),
                ('amount2', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='مبلغ المركز الثاني')),
                ('rate', models.DecimalField(decimal_places=6, default=1, max_digits=14, verbose_name='سعر الصرف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='بواسطة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'تبديل عملة',
                'verbose_name_plural': 'تبديلات العملات',
                'ordering': ['-created_at'],
            },
        ),
    ]
