# Generated by Django 4.2 on 2026-05-10 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_currency_swap'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutAndClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=30, unique=True, verbose_name='رقم السند')),
                ('buy_center', models.CharField(max_length=200, verbose_name='مركز الشراء')),
                ('buy_currency', models.CharField(max_length=10, verbose_name='عملة الشراء')),
                ('buy_amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='مبلغ الشراء')),
                ('buy_rate', models.DecimalField(decimal_places=6, default=1, max_digits=14, verbose_name='سعر قص الشراء')),
                ('buy_dir', models.CharField(choices=[('mul', '× ضرب'), ('div', '÷ قسمة')], default='div', max_length=3, verbose_name='اتجاه قص الشراء')),
                ('buy_usd', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='قيمة الشراء بالدولار')),
                ('buy_notes', models.TextField(blank=True, verbose_name='ملاحظات الشراء')),
                ('sell_center', models.CharField(max_length=200, verbose_name='مركز البيع')),
                ('sell_currency', models.CharField(max_length=10, verbose_name='عملة البيع')),
                ('sell_amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='مبلغ البيع')),
                ('sell_rate', models.DecimalField(decimal_places=6, default=1, max_digits=14, verbose_name='سعر قص البيع')),
                ('sell_dir', models.CharField(choices=[('mul', '× ضرب'), ('div', '÷ قسمة')], default='div', max_length=3, verbose_name='اتجاه قص البيع')),
                ('sell_usd', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='قيمة البيع بالدولار')),
                ('sell_notes', models.TextField(blank=True, verbose_name='ملاحظات البيع')),
                ('profit_usd', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='الربح بالدولار')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='بواسطة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'قص وإغلاق',
                'verbose_name_plural': 'سندات القص والإغلاق',
                'ordering': ['-created_at'],
            },
        ),
    ]
