# Generated by Django 4.2 on 2026-05-10 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0043_cut_and_close'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('account_no', models.CharField(max_length=30, unique=True, verbose_name='رقم الحساب')),
                ('account_type', models.CharField(choices=[('client', 'عميل'), ('agent', 'وكيل'), ('branch', 'فرع'), ('treasury', 'خزينة'), ('other', 'أخرى')], default='client', max_length=20, verbose_name='نوع الحساب')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='العملة الأساسية')),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='الرصيد')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='هاتف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='أنشأه')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'دليل الحسابات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SettlementVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=30, unique=True, verbose_name='رقم السند')),
                ('center_name', models.CharField(max_length=200, verbose_name='المركز المرسل')),
                ('total_us', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='إجمالي لنا')),
                ('total_them', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='إجمالي علينا')),
                ('net_profit', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='صافي الربح')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='بواسطة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'قيد تسوية',
                'verbose_name_plural': 'قيود التسوية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='العملة')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='المبلغ')),
                ('fee_us', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='أجور لنا')),
                ('beneficiary', models.CharField(blank=True, max_length=200, verbose_name='المستفيد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='الوجهة')),
                ('fee_them', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='أجور علينا')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='pages.settlementvoucher', verbose_name='السند')),
            ],
            options={
                'verbose_name': 'صف تسوية',
                'verbose_name_plural': 'صفوف التسوية',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(max_length=30, unique=True, verbose_name='رقم القيد')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='المبلغ')),
                ('from_currency', models.CharField(default='USD', max_length=10, verbose_name='عملة المصدر')),
                ('to_currency', models.CharField(default='USD', max_length=10, verbose_name='عملة الوجهة')),
                ('cut_rate', models.DecimalField(decimal_places=6, default=1, max_digits=14, verbose_name='سعر القص')),
                ('cut_dir', models.CharField(choices=[('mul', '× ضرب'), ('div', '÷ قسمة')], default='mul', max_length=3, verbose_name='اتجاه القص')),
                ('to_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='المبلغ المحوَّل')),
                ('profit', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='الربح')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.CharField(blank=True, max_length=150, verbose_name='بواسطة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries_from', to='pages.accountledger', verbose_name='حساب المصدر (دَين)')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries_to', to='pages.accountledger', verbose_name='حساب الوجهة (دائن)')),
            ],
            options={
                'verbose_name': 'قيد محاسبي',
                'verbose_name_plural': 'القيود المحاسبية',
                'ordering': ['-created_at'],
            },
        ),
    ]
