# Generated by Django 4.2 on 2026-05-10 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0044_journal_settlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('from_center', models.CharField(max_length=200)),
                ('from_name', models.CharField(blank=True, max_length=200)),
                ('from_currency', models.CharField(default='USD', max_length=10)),
                ('from_amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('from_fee', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('from_fee_cur', models.CharField(default='USD', max_length=10)),
                ('from_notes', models.TextField(blank=True)),
                ('cut_rate', models.DecimalField(decimal_places=6, default=1, max_digits=14)),
                ('cut_dir', models.CharField(choices=[('mul', '× ضرب'), ('div', '÷ قسمة')], default='mul', max_length=3)),
                ('to_center', models.CharField(max_length=200)),
                ('to_beneficiary', models.CharField(blank=True, max_length=200)),
                ('to_currency', models.CharField(default='USD', max_length=10)),
                ('to_amount', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('to_fee', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('to_fee_cur', models.CharField(default='USD', max_length=10)),
                ('to_notes', models.TextField(blank=True)),
                ('cut_diff', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('net_profit', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
