# Generated by Django 4.2 on 2026-05-11 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0045_advanced_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_username', models.CharField(max_length=150, unique=True, verbose_name='اسم مستخدم المشرف')),
                ('supervisor_name', models.CharField(blank=True, max_length=150, verbose_name='الاسم المعروض')),
                ('balance_usd', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='رصيد دولار')),
                ('balance_ils', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='رصيد شيكل')),
                ('balance_jod', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='رصيد دينار')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'صندوق مشرف',
                'verbose_name_plural': 'صناديق المشرفين',
            },
        ),
        migrations.CreateModel(
            name='SupervisorBoxLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_username', models.CharField(max_length=150, verbose_name='المشرف')),
                ('op_type', models.CharField(choices=[('deposit', 'إيداع من الإدارة'), ('distribute', 'توزيع على تلر'), ('reclaim', 'استرداد من تلر')], max_length=12)),
                ('currency', models.CharField(choices=[('USD', 'دولار'), ('ILS', 'شيكل'), ('JOD', 'دينار')], default='USD', max_length=3)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('teller_username', models.CharField(blank=True, max_length=150, verbose_name='التلر (عند التوزيع)')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'حركة صندوق مشرف',
                'verbose_name_plural': 'حركات صناديق المشرفين',
                'ordering': ['-created_at'],
            },
        ),
    ]
