# Generated by Django 4.2 on 2026-05-11 09:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0046_supervisor_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='TellerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=30, unique=True, verbose_name='رقم الجلسة')),
                ('teller_username', models.CharField(db_index=True, max_length=150, verbose_name='التلر')),
                ('teller_name', models.CharField(blank=True, max_length=150)),
                ('opened_by', models.CharField(blank=True, max_length=150, verbose_name='فُتحت بواسطة')),
                ('status', models.CharField(choices=[('pending', 'في انتظار التأكيد'), ('open', 'مفتوحة'), ('closed', 'مغلقة')], default='pending', max_length=10)),
                ('opening_usd', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('opening_ils', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('opening_jod', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('closing_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('closing_ils', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('closing_jod', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('closing_note', models.TextField(blank=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'جلسة تلر',
                'verbose_name_plural': 'جلسات التلرات',
                'ordering': ['-opened_at'],
            },
        ),
    ]
