# Generated by Django 4.2 on 2026-05-13 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_tellersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePagePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=4, unique=True, verbose_name='الدور')),
                ('pages', models.JSONField(default=list, verbose_name='الصفحات المسموح بها')),
                ('updated_by', models.CharField(blank=True, max_length=150, verbose_name='عُدِّل بواسطة')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'صلاحيات دور',
                'verbose_name_plural': 'صلاحيات الأدوار',
            },
        ),
    ]
