# Generated by Django 4.2 on 2026-05-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0048_add_role_page_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tellerpermission',
            name='accounts',
            field=models.BooleanField(default=True, verbose_name='إدارة الحسابات'),
        ),
    ]
