# Generated by Django 4.2 on 2026-05-24 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0057_cost_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('screen', 'سعر الشاشة'), ('balance', 'سعر قص الرصيد'), ('movement', 'سعر قص الحركات')], max_length=20, verbose_name='نوع السعر')),
                ('currency', models.CharField(max_length=10, verbose_name='العملة')),
                ('rate', models.DecimalField(decimal_places=6, default=1, max_digits=14, verbose_name='السعر')),
                ('direction', models.CharField(choices=[('mul', '× ضرب'), ('div', '÷ قسمة')], default='div', max_length=3, verbose_name='الاتجاه')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سعر قص',
                'verbose_name_plural': 'أسعار القص',
                'ordering': ['price_type', 'currency'],
            },
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
