# Generated by Django 4.2 on 2026-05-24 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0058_cut_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_type', models.CharField(choices=[('balance', 'تفريق قص الرصيد'), ('movement', 'تفريق قص الحركات'), ('system', 'تفريق قص النظام')], max_length=20, verbose_name='نوع التفريق')),
                ('center_name', models.CharField(max_length=200, verbose_name='المركز')),
                ('from_value', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='من')),
                ('to_value', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='إلى')),
                ('distribution', models.DecimalField(decimal_places=4, default=0, max_digits=14, verbose_name='التفريق')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تفريق قص',
                'verbose_name_plural': 'تفريقات القص',
                'ordering': ['dist_type', 'center_name'],
            },
        ),
    ]
