# Generated by Django 4.2 on 2026-05-24 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0059_cut_distribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم العملة')),
                ('symbol', models.CharField(max_length=10, verbose_name='الرمز')),
                ('multiplier', models.DecimalField(decimal_places=6, default=1, max_digits=14, verbose_name='المعامل')),
                ('eval_rate', models.DecimalField(decimal_places=6, default=1, max_digits=14, verbose_name='سعر التقييم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('updated_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات',
                'ordering': ['name'],
            },
        ),
    ]
